id = "lammps"
name = "LAMMPS"
version = "0.5.3"
schema_version = 1
authors = ["crack-time"]
description = "LAMMPS input script support with syntax highlighting, hover documentation, and diagnostics"
repository = "https://github.com/crack-time/lammps-zed"
license = "MIT"

[grammars.lammps]
repository = "https://github.com/crack-time/lammps-tree-sitter"
commit = "0ec2a367bcdfc4cd70656ef5f44523d31da406fa"

[language_servers.lammps-lsp]
name = "LAMMPS LSP"
language = "LAMMPS"
