id = "lammps"
name = "LAMMPS"
version = "0.5.3"
schema_version = 1
authors = ["crack-time"]
description = "LAMMPS input script support with syntax highlighting, hover documentation, and diagnostics"
repository = "https://github.com/crack-time/lammps-zed"
license = "MIT"

[grammars.lammps]
repository = "https://github.com/crack-time/lammps-tree-sitter"
commit = "588f375d2490b065be7ff5ff921f8b8b55ba8f6f"

[language_servers.lammps-lsp]
name = "LAMMPS LSP"
language = "LAMMPS"
