name = "LAMMPS"
grammar = "lammps"
scope = "source.lammps"
injection_regex = "lammps"
path_suffixes = ["lmp", "lmps", "lammps", "in"]
autoclose_before = "{[(,"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
]
line_comment = "#"

