name = "LAMMPS"
scope = "source.lammps"
injection_regex = "lammps"
file_types = ["lmp", "lmps", "lammps", "in.*", "*.lammps"]
autoclose_before = "{[(,"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
]

[tree_sitter]
syntax = "source.lammps"

[language_servers.lammps-lsp]
